language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-python-dev
  - sudo apt-get install g++-4.9

# command to install
install: "CC=/usr/bin/gcc-4.9 sudo pip install ."

# command to run tests
script: nosetest
 
