language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-add-repository ppa:cython-dev/master-ppa -y
  - sudo apt-get -qq update
  - sudo apt-get install -qq libboost-python1.55-dev
  - sudo apt-get install -qq gcc-4.9
  - sudo apt-get install -qq g++-4.9
  - pip install nose
  - pip install mpmath
  - pip install numpy

install: 
#  - CC=/usr/bin/gcc-4.9 pip install .[pycas]
  - CC=/usr/bin/gcc-4.9 python setup.py install 

script: nosetests
 
notifications:
  email: false

