language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:boost-latest/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -qq libboost-all-dev
  - sudo apt-get install -qq gcc-4.9
  - sudo apt-get install -qq g++-4.9

# command to install
install: "CC=/usr/bin/gcc-4.9 sudo pip install ."

# command to run tests
script: nosetest
 
